const id = (value: string | number) => encodeURIComponent(String(value));

export const API_PATHS = {
    CLIENT_CONFIG: '/client-config',
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    PASSWORD: '/auth/password',
    ADMIN_UI: '/admin/index.html',
    TENANTS: '/tenants',
    ADMISSIONS: '/admissions',
    ROOMS: '/rooms',
    LEDGER: '/ledger',
    INVOICES: '/invoices',
    INVOICES_GENERATE_CYCLE: '/invoices/generate-cycle',
    LEDGER_BALANCE: '/ledger/balance',
    SYSTEM_CLEAN_DATABASE: '/system/clean-database',
    PROPERTIES: '/properties',
    tenant: (uid: string) => `/tenants/${id(uid)}`,
    tenantsInRoom: (room: string) => `/tenants/room/${id(room)}`,
    verifyAdvance: (uid: string) => `/tenants/${id(uid)}/verify-advance`,
    admission: (number: string) => `/admissions/${id(number)}`,
    confirmAdmission: (number: string) => `/admissions/${id(number)}/confirm`,
    CHECK_EXISTING: '/admissions/check-existing',
    room: (number: string) => `/rooms/${id(number)}`,
    payInvoice: (invoiceId: string) => `/invoices/${id(invoiceId)}/pay`,
    property: (propertyId: number) => `/properties/${id(propertyId)}`,
    user: (userId: number) => `/users/${id(userId)}`,
    USERS: '/users',
} as const;
